.PHONY: build
.DEFAULT_GOAL := build

build:
	 docker build -t task1 -f task1.Dockerfile .
	 docker build -t task2 -f task2.Dockerfile .
	 docker build -t task3 -f task3.Dockerfile .
	 docker build -t gate -f gate.Dockerfile .
